package edu.escuelaing.arep;

/**
 * The RestService interface provides a contract for implementing RESTful services.
 * Classes that implement this interface must define a method to process an incoming
 * request and return a response.
 */
public interface RestService {
    /**
     * Processes an incoming request and generates a response.
     * The specific behavior of this method depends on the implementation.
     *
     * @param request the input request string, which may contain parameters or other data.
     * @return a string containing the response generated by processing the request.
     */
    public String response(String request);
}
